services:
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    networks:
      - app-network
    command: ["npm", "test"]

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    volumes:
      - ./backend:/app
    networks:
      - app-network
    command: ["npm", "run", "test"]

networks:
  app-network:
    driver: bridge
